# Generated by Django 3.2.7 on 2022-02-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='zip',
            new_name='pin',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='KYCDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('aadhar_number', models.IntegerField(unique=True)),
                ('pan', models.CharField(max_length=12, unique=True)),
                ('kyc_status', models.IntegerField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=80)),
                ('bank_address', models.CharField(max_length=80)),
                ('branch_code', models.CharField(max_length=80)),
                ('ifsc', models.CharField(max_length=80)),
                ('account_number', models.IntegerField(unique=True)),
                ('swift_code', models.CharField(max_length=80)),
                ('is_active', models.BooleanField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
